"""estrutura inicial

Revision ID: eed42955c620
Revises:
Create Date: 2026-06-16 14:41:22.089370

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "eed42955c620"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Aplica a migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contatos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telefone", sa.String(length=32), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=True),
        sa.Column("opt_out", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contatos_telefone"), "contatos", ["telefone"], unique=True)
    op.create_table(
        "promocoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column("vigencia_inicio", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vigencia_fim", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ativa", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assunto", sa.String(length=64), nullable=False),
        sa.Column("gatilho", sa.String(length=255), nullable=True),
        sa.Column("conteudo", sa.Text(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("aprovado_meta", sa.Boolean(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_templates_assunto"), "templates", ["assunto"], unique=False)
    op.create_table(
        "agendamentos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contato_id", sa.Integer(), nullable=False),
        sa.Column("servico", sa.String(length=255), nullable=False),
        sa.Column("data_hora", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pendente",
                "confirmado",
                "cancelado",
                "concluido",
                name="statusagendamento",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contato_id"], ["contatos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agendamentos_contato_id"), "agendamentos", ["contato_id"], unique=False
    )
    op.create_table(
        "conversas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contato_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "nova",
                "em_andamento",
                "aguardando_humano",
                "agendamento",
                "encerrada",
                name="estadoconversa",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("em_atendimento_humano", sa.Boolean(), nullable=False),
        sa.Column("ultima_msg_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "ultima_msg_origem",
            sa.Enum("cliente", "bot", "humano", name="origemmensagem", native_enum=False),
            nullable=True,
        ),
        sa.Column("intencao_atual", sa.String(length=64), nullable=True),
        sa.Column("ultima_msg_cliente_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "dados_fluxo",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contato_id"], ["contatos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversas_contato_id"), "conversas", ["contato_id"], unique=False)
    op.create_table(
        "eventos_metrica",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=64), nullable=False),
        sa.Column("conversa_id", sa.Integer(), nullable=True),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversa_id"], ["conversas.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_eventos_metrica_conversa_id"), "eventos_metrica", ["conversa_id"], unique=False
    )
    op.create_index(op.f("ix_eventos_metrica_tipo"), "eventos_metrica", ["tipo"], unique=False)
    op.create_table(
        "mensagens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversa_id", sa.Integer(), nullable=False),
        sa.Column("wa_message_id", sa.String(length=128), nullable=True),
        sa.Column(
            "origem",
            sa.Enum("cliente", "bot", "humano", name="origemmensagem", native_enum=False),
            nullable=False,
        ),
        sa.Column("texto", sa.Text(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "texto",
                "interativo",
                "imagem",
                "audio",
                "video",
                "documento",
                "localizacao",
                "outro",
                name="tipomensagem",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "recebida",
                "enviada",
                "entregue",
                "lida",
                "falha",
                name="statusmensagem",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload_interativo", sa.String(length=256), nullable=True),
        sa.Column(
            "recebida_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("respondida", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["conversa_id"], ["conversas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wa_message_id"),
    )
    op.create_index(op.f("ix_mensagens_conversa_id"), "mensagens", ["conversa_id"], unique=False)
    op.create_table(
        "intencoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mensagem_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("confianca", sa.Float(), nullable=False),
        sa.Column("modelo", sa.String(length=64), nullable=False),
        sa.Column(
            "criado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["mensagem_id"], ["mensagens.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_intencoes_mensagem_id"), "intencoes", ["mensagem_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte a migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_intencoes_mensagem_id"), table_name="intencoes")
    op.drop_table("intencoes")
    op.drop_index(op.f("ix_mensagens_conversa_id"), table_name="mensagens")
    op.drop_table("mensagens")
    op.drop_index(op.f("ix_eventos_metrica_tipo"), table_name="eventos_metrica")
    op.drop_index(op.f("ix_eventos_metrica_conversa_id"), table_name="eventos_metrica")
    op.drop_table("eventos_metrica")
    op.drop_index(op.f("ix_conversas_contato_id"), table_name="conversas")
    op.drop_table("conversas")
    op.drop_index(op.f("ix_agendamentos_contato_id"), table_name="agendamentos")
    op.drop_table("agendamentos")
    op.drop_index(op.f("ix_templates_assunto"), table_name="templates")
    op.drop_table("templates")
    op.drop_table("promocoes")
    op.drop_index(op.f("ix_contatos_telefone"), table_name="contatos")
    op.drop_table("contatos")
    # ### end Alembic commands ###
